### ISSUE TITLE
Would it be possible to remove testify?

### ISSUE THREAD

**Issue by user19820** [noquark/nanoid#1]
Hello,

I am not sure if this is a valid issue, but as a developer I prefer to avoid unneeded dependencies if possible. Testify is a nice package, but it is a huge dependency I typically avoid when writing my code. Would you entertain removing testify for standard library testing or a smaller dependency like [matryer/is](https://github.com/matryer/is)? 
I would be willing to write a PR for this if the work is too much.

Thanks for considering!

**Comment by mohitsinghs** [comment]
Hi @akalpaki, Thanks for suggesting this. Testify was indeed an overkill here I think. I've dropped it for standard library.
